language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew
after_failure:
 - cat build/reports/*/*.xml
cache:
 directories:
  - $HOME/.m2
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches
notifications:
  slack: tecnicas7510-01-2016:43BRCtpL4l34RXwewR6Lv3z4
